export const LOAD = 'LOAD';

export const UPDATE_PERSONALITY = 'UPDATE_PERSONALITY';

export const ADD_XP = 'ADD_XP';
export const UPDATE_ABILITIES = 'UPDATE_ABILITIES';

export const UPDATE_CHARACTER = 'UPDATE_CHARACTER';

export const REMOVE_ITEM = 'REMOVE_ITEM';
export const ADD_TO_WALLET = 'ADD_TO_WALLET';
export const REMOVE_FROM_WALLET = 'REMOVE_FROM_WALLET';